config:
  run_type: cron
  cron_interval: "0 5 * * *"
  keyfile: "/var/opt/gitsync/keys/id_rsa"

repos:
  my_repo_1:
    github:
      url: "git@github.com:torvalds/linux"
      source: true
    gitlab: 
      url: "ssh://git@gitlab.example.com:54321/torvalds/linux.git"
