config:
  run_type: cron
  cron_interval: "0 5 * * *"
  keyfile: "/home/gitsync/.ssd/id_ed25519"

repos:
  my_repo_1:
    github:
      url: "git@github.com:torvalds/linux"
      source: true
    gitlab: 
      url: "ssh://git@gitlab.com:22/torvalds/linux.git"
